apiVersion: v1
kind: Service
metadata:
  name: {{ include "octane.fullname" . }}
  labels:
    {{- include "octane.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "octane.selectorLabels" . | nindent 4 }}
    octane/pod-type: web
